In [177]:
import pandas as pd 
import numpy as np

#读取数据，了解基本情况
df = pd.read_excel('data.xlsx',index_col=0)
print("数据表的行列为：",df.shape)
print('获取列名\n',df.columns)

#各列数据类型和，空值情况
df.info()

#数值型数据的描述性分布
df.describe()
df.head()

数据表的行列为： (1430, 26)
获取列名
 Index(['应聘职位', '性别', '出生日期', '年龄', '居住地', '期望薪资', '地点', '职能/职位', '行业', '工作类型',
       '学校', '办学类型', '专业', '工作经验', '工作时间', '公司名称', '公司规模', '公司行业', '性质', '部门',
       '职位', '工作公司数', '工作年限', '工作稳定性', '是否稳定', '技能/语言'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1430 entries, 1 to 1430
Data columns (total 26 columns):
应聘职位     1430 non-null object
性别       1430 non-null object
出生日期     1430 non-null datetime64[ns]
年龄       1430 non-null int64
居住地      1430 non-null object
期望薪资     1407 non-null object
地点       1409 non-null object
职能/职位    1430 non-null object
行业       1149 non-null object
工作类型     1430 non-null object
学校       1430 non-null object
办学类型     1430 non-null object
专业       1420 non-null object
工作经验     1348 non-null object
工作时间     1430 non-null object
公司名称     1430 non-null object
公司规模     1430 non-null object
公司行业     1430 non-null object
性质       1430 non-null object
部门       1430 non-null object
职位       1430 non-null object
工作公司数    1430 non-null int64
工作年限     1430 non-null object
工作稳定性    1430 non-null int64
是否稳定     1430 non-null object
技能/语言    578 non-null object
dtypes: datetime64[ns](1), int64(3), object(22)
memory usage: 301.6+ KB

,应聘职位,性别,出生日期,年龄,居住地,期望薪资,地点,职能/职位,行业,工作类型,...,公司规模,公司行业,性质,部门,职位,工作公司数,工作年限,工作稳定性,是否稳定,技能/语言
简历号,,,,,,,,,,,,,,,,,,,,,
1,平面设计师,男,1990-12-01,29,武汉-武昌区,5000-10000元/月,武汉,软件工程师 Java开发工程师,计算机软件,全职,...,50-150人,计算机软件,国企,研发部,Java开发工程师,4,5年,1,不稳定,Mybatie(熟练) JSP(熟练) mysql(熟练) Hibernate(熟练)...
2,平面设计师,男,1996-08-01,23,武汉-江夏区,5999-7999元/月,武汉,软件工程师 Java开发软件工程师,计算机软件,全职,...,10000人以上,计算机软件,上市公司,后端6组,Java开发工程师,1,2年,2,较稳定,HTML5(熟练) CSS(良好) SSM(熟练) C/C++(良好) SSH(良好...
3,平面设计师,男,1993-06-01,26,武汉-武昌区,8-10万元/年,武汉,软件工程师 Linux开发工程师,计算机软件,全职,...,无,计算机软件,民营公司,开发部,系统工程师,1,2年,2,较稳定,NaN
4,平面设计师,男,1991-03-01,28,武汉,6000-7999元/月,武汉,软件工程师 Java开发工程师,计算机软件,全职,...,50-150人,计算机软件,民营公司,Java开发,Java开发工程师,1,2年,2,较稳定,"Struts2,Hibernate,Spring,Mybatis等框架的使用并整合(熟练) ..."
5,平面设计师,男,1995-09-01,24,长沙-岳麓区,4500-5999元/月,武汉,软件工程师 ERP实施顾问 软件实施工程师,计算机软件,全职,...,无,计算机软件,民营公司,java技术组,Java开发工程师,1,2年,2,较稳定,SQL(良好)

In [178]:
#开始处理G列——即“期望薪资”

#G列填充空值为‘无’
#注意到只有1407个数据，说明可能存在其他形式的null，比如na，nan
e_salary = df['期望薪资']
print(e_salary.isnull().sum()) # 有23个空值，1407加23正好1430
e_salary = e_salary.fillna('无')
print(e_salary.isnull().sum())


import re
#找到薪资单位不同的行索引
index_year= e_salary[e_salary.str.contains('年')].index
index_10000= e_salary[e_salary.str.contains('万')].index
print(index_year)
print(index_10000)

#切分出薪资数字
num_salary = e_salary.str.findall('^\d+-\d+')
num_salary=num_salary.astype("str")
print(type(num_salary[1]))#元素为str

#划分薪资上限下限
low = pd.Series()
high = pd.Series()
low,high = num_salary.str.split('-',1).str
#[''],需要反斜杠转义
low = low.str.split("\[\'").str[1]
high = high.str.split("\'\]").str[0]
# print(low,high)
df['low'] = low.astype('float')
df['high'] = high.astype('float')

# 汉字单位统一为元/月,根据年&万单位的索引进行统一
df.loc[index_10000,['low','high']]= df.loc[index_10000,['low','high']]*10000
df.loc[index_year,['low','high']] = df.loc[index_year,['low','high']]/12

# 得到期望薪资上下限，单位元/月，
# print(df['low'],df['high'])
print(np.isnan(df['low']))

23
0
Int64Index([   3,   15,   26,   38,   45,   50,   51,   60,   63,   64,
            ...
            1346, 1354, 1364, 1365, 1392, 1404, 1409, 1410, 1412, 1415],
           dtype='int64', name='简历号', length=154)
Int64Index([   3,   15,   26,   38,   45,   50,   51,   60,   63,   64,
            ...
            1339, 1346, 1354, 1364, 1365, 1392, 1404, 1409, 1412, 1415],
           dtype='int64', name='简历号', length=141)
<class 'str'>
简历号
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19       True
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
30      False
        ...
1401    False
1402    False
1403     True
1404    False
1405    False
1406    False
1407    False
1408    False
1409    False
1410    False
1411    False
1412    False
1413    False
1414    False
1415    False
1416    False
1417    False
1418    False
1419    False
1420    False
1421    False
1422    False
1423    False
1424    False
1425    False
1426    False
1427    False
1428    False
1429    False
1430    False
Name: low, Length: 1430, dtype: bool

In [196]:
#重新检查df的列
df.head()

,应聘职位,性别,出生日期,年龄,居住地,期望薪资,地点,职能/职位,行业,工作类型,...,部门,职位,工作公司数,工作年限,工作稳定性,是否稳定,技能/语言,low,high,期望薪资分类
简历号,,,,,,,,,,,,,,,,,,,,,
1,平面设计师,男,1990-12-01,29,武汉-武昌区,5000-10000元/月,武汉,软件工程师 Java开发工程师,计算机软件,全职,...,研发部,Java开发工程师,4,5年,1,不稳定,Mybatie(熟练) JSP(熟练) mysql(熟练) Hibernate(熟练)...,5000.000000,10000.000000,4000-5999
2,平面设计师,男,1996-08-01,23,武汉-江夏区,5999-7999元/月,武汉,软件工程师 Java开发软件工程师,计算机软件,全职,...,后端6组,Java开发工程师,1,2年,2,较稳定,HTML5(熟练) CSS(良好) SSM(熟练) C/C++(良好) SSH(良好...,5999.000000,7999.000000,4000-5999
3,平面设计师,男,1993-06-01,26,武汉-武昌区,8-10万元/年,武汉,软件工程师 Linux开发工程师,计算机软件,全职,...,开发部,系统工程师,1,2年,2,较稳定,NaN,6666.666667,8333.333333,6000-7999
4,平面设计师,男,1991-03-01,28,武汉,6000-7999元/月,武汉,软件工程师 Java开发工程师,计算机软件,全职,...,Java开发,Java开发工程师,1,2年,2,较稳定,"Struts2,Hibernate,Spring,Mybatis等框架的使用并整合(熟练) ...",6000.000000,7999.000000,6000-7999
5,平面设计师,男,1995-09-01,24,长沙-岳麓区,4500-5999元/月,武汉,软件工程师 ERP实施顾问 软件实施工程师,计算机软件,全职,...,java技术组,Java开发工程师,1,2年,2,较稳定,SQL(良好),4500.000000,5999.000000,4000-5999

In [209]:
#开始处理AA列技能
e_skill = df['技能/语言']#在第一格列的情况里，只有578个数据，所以查看空值情况
print(e_skill[3],type(e_skill[2]))
print(e_skill.isnull().sum().sum()) #空值为852

# 空值补充为“无”
e_skill = e_skill.fillna('无')
print(e_skill.isnull().sum().sum())


#查找是否包含 Photoshop,photoshop,PS,ps,  Corel Draw, corel draw, AI
#三选3，选2，选1， 0，不区分大小写，前后非字母

nan <class 'str'>
852
0